### ISSUE TITLE
Integrasi dengan MongoDB

### ISSUE THREAD

**Issue by praswicaksono** [MalangPHP/singo#16]
Integrasi dengan MongoDB

**Comment by reyhansofian** [comment]
Apakah hanya integrasi dengan MongoDB? Lalu apakah ini hanya membuat koneksi ke MongoDB saja atau membuat grammar nya untuk memfasilitasi CRUD dengan MongoDB?

**Comment by praswicaksono** [comment]
hanya buat ODM (Object-document mapping), sama seperti ORM

library ODM untuk saat ini : http://doctrine-mongodb-odm.readthedocs.org/en/latest/

kalau ada library ODM lain silahkan di share
