### ISSUE TITLE
[RFC] Console Application

### ISSUE THREAD

**Issue by praswicaksono** [MalangPHP/singo#33]
Ability to create command line based app.

**Comment by reyhansofian** [comment]
Parameter nya apa saja?

**Comment by praswicaksono** [comment]
flexsibel sam, application extend https://github.com/symfony/Console

jadi nanti di Module.php ada fungsi registerCliCommand buat registrasi cli command

**Comment by praswicaksono** [comment]
cek : https://github.com/MalangPHP/singo/blob/2.0/tests/Singo/Tests/CliApplicationTest.php

**Comment by maman** [comment]
maksudnya command-line based gmn?
kalo semacem artisan gitu kayak e oke, tapi lek misal bikin command line app dari singo kok rasane malih bloated .. keep it simple and stupid ae sam

**Comment by praswicaksono** [comment]
nah, artisan itu nanti berupa module yang dibuat dari applikasi CLI. nanti modulenya juga fleksible, ga harus MVC yang ada di dalam module. misal module apps CLI, module khusus service, module khusus entity dll.
