### ISSUE TITLE
[FEATURE] Dokumentasi berbahasa inggris

### ISSUE THREAD

**Issue by praswicaksono** [MalangPHP/singo#5]
Bagi yang merasa bahasa inggirsnya jago monggo kirim pull request untuk dokumentasi berbahasa indonesia

**Comment by santosoide** [comment]
lha dokumentasinya nanti taruh mana? direpository ini apa repository berbeda

**Comment by praswicaksono** [comment]
nah itu mending taroh repo beda, bikin gh pages aja kalo menurutku.
